### ISSUE TITLE
Add FSharPlus.Data types

### ISSUE THREAD

**Issue by gusty** [fsprojects/Fleece#101]
I was wondering, since F#+ is anyway a dependency of this project, is there any drawback in adding F#+ Data types like NonEmptyList and so on, to the overload list ?

At the moment I can't think of any downside.

**Comment by Choc13** [comment]
This would be a great addition. I had to write one for `NonEmptyList` and although easy to write it would be great to get out of the box here.

**Comment by gusty** [comment]
This was completed in 0.10.0
