### ISSUE TITLE
Nuget api v3 can not resolve Fleece.NewtonsoftJson

### ISSUE THREAD

**Issue by vchekan** [fsprojects/Fleece#62]
Trying to use a package where `Fleece.NewtonsoftJson` is a transient dependency. My paket's source is v3: `https://api.nuget.org/v3/index.json` . When issuing `paket install`, got error:
```
  Conflict detected:
   - Fleece.NewtonsoftJson 0.7.0 requested package FSharpPlus: >= 1.1.0-CI00245 (CI)
   - Available versions:
     - (1.1.0-ci00252, [https://api.nuget.org/v3/index.json])
     - (1.1.0-ci00245, [https://api.nuget.org/v3/index.json])
...
```
Notice different in caps casing of CI. 
Change paket's source to `https://www.nuget.org/api/v2` and `paket install` works fine.

Expected behavior: `Fleece.NewtonsoftJson` should resolve vor v2 and v3 api version of nuget.

**Comment by wallymathieu** [comment]
So given a official release this could be alleviated

**Comment by wallymathieu** [comment]
We have a 0.8.0 release out now, is this still an issue?

**Comment by gusty** [comment]
No response, I assume it's solved, otherwise please re-open.
