### ISSUE TITLE
Move to FsProjects

### ISSUE THREAD

**Issue by gusty** [fsprojects/Fleece#74]
We would like to move this library to FsProjects.

@forki can you do the move? @mausch will do whatever you need to complete the move.

Thanks !

**Comment by forki** [comment]
@mausch I think you need to make me a member or administrator. Then transfer ownership to me. I'll then transfer it to fsprojects.

**Comment by mausch** [comment]
@forki thanks! Just sent you an invite

**Comment by forki** [comment]
Ok accepted. You should now be able to transfer it to me

Mauricio Scheffer <notifications@github.com> schrieb am Fr., 8. Mai 2020,
19:59:

**Comment by mausch** [comment]
Done, it's https://github.com/fsprojects/Fleece now :tada:

**Comment by forki** [comment]
ah looks like you were able to transfer it directly. Now I'm adding a mainainers group. Please let me know who should be in there?

**Comment by mausch** [comment]
Yeah not sure what I clicked there :-) 
Anyway @gusty and @wallymathieu for sure, and of course it's up to them to decide if they want to add anyone else!
Cheers

**Comment by forki** [comment]
ok done. thanks everyone. Next steps:

1) please add a section about current maintainers in ReadMe
2) decide if you want to add a CoC (please do)
